services:
  db:
    image: mysql:8.0
    container_name: oracle_hr_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password # I know it's sensitive but it's fine
      MYSQL_DATABASE: OLAP
    ports:
      - 3307:3306
    volumes:
      - data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/data
      - ./my.cnf:/etc/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --secure-file-priv=docker-entrypoint-initdb.d --local-infile

  api:
    build: .
    container_name: oracle_hr_api
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

volumes:
  data:
